is_official_build = true
is_debug = false
is_component_build = false
target_os = "mac"
target_cpu = "arm64"
skia_use_fonthost_mac = true
skia_use_freetype = true
skia_use_system_freetype2 = false
skia_enable_fontmgr_custom_embedded = true
skia_enable_fontmgr_custom_directory = false
skia_enable_fontmgr_custom_empty = false
skia_enable_fontmgr_android = false
skia_enable_fontmgr_android_ndk = false
skia_use_fontconfig = false
skia_use_fontations = false
skia_use_system_libpng = false
skia_use_system_zlib = false
skia_use_libpng_decode = true
skia_use_libpng_encode = true
skia_use_freetype_zlib = true
skia_use_freetype_woff2 = false
skia_use_freetype_svg = false
skia_enable_ganesh = false
skia_enable_graphite = false
skia_enable_pdf = false
skia_enable_skottie = false
skia_enable_svg = false
skia_enable_tools = false
skia_use_harfbuzz = false
skia_use_icu = false
skia_use_expat = false
skia_use_libjpeg_turbo_decode = false
skia_use_libjpeg_turbo_encode = false
skia_use_libwebp_decode = false
skia_use_libwebp_encode = false
skia_use_wuffs = false
skia_use_piex = false
skia_use_dng_sdk = false
skia_use_perfetto = false
skia_use_lua = false
skia_use_xps = false
